# Generated by Django 3.1 on 2020-08-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_available',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
