# Generated by Django 3.1 on 2020-08-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_auto_20200814_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='worker',
            name='last_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='worker',
            name='primary_phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='worker',
            name='secondary_phone',
            field=models.CharField(max_length=10),
        ),
    ]
