# Generated by Django 3.1 on 2020-08-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0007_auto_20200814_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='gr_codes'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='first_name',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='worker',
            name='last_name',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='worker',
            name='secondary_phone',
            field=models.TextField(max_length=10),
        ),
    ]
