# Generated by Django 3.1 on 2020-08-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0008_auto_20200815_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='worker',
            name='last_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='worker',
            name='primary_phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='worker',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_code'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='secondary_phone',
            field=models.CharField(max_length=10),
        ),
    ]
